development:
  adapter: postgresql
  encoding: unicode
  database: tracktor_development
  pool: 5
  username: efatsi
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: tracktor_test
  pool: 5
  username: efatsi
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: tracktor_production
  pool: 5
  username: efatsi
  password:
